alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias l='ls -ll'

alias g='git'
alias gst='git status'
alias gco='git checkout'
alias gcd='git checkout development'
alias gcs='git checkout staging'
alias gcp='git checkout production'
alias gmd='git merge development'

alias be='bundle exec'
alias rs='bundle exec rspec'
alias r='bundle exec rails'
alias rk='bundle exec rake'
alias tu='bundle exec rake test:units'
alias tf='bundle exec rake test:controllers'

